version: 0.0
os: linux

files:
  - source: dist # ✅ Deploy built Vite files
    destination: /var/www/react-app/dist

  - source: package.json # ✅ Deploy package.json (needed for npm install)
    destination: /var/www/react-app

  - source: package-lock.json # ✅ Ensures correct dependency versions
    destination: /var/www/react-app

permissions:
  - object: /var/www/react-app
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 120
      runas: ec2-user

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 60
      runas: ec2-user
