version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the React Vite app..."
      - npm run build

artifacts:
  files:
    - "dist/**" # ✅ Vite outputs to 'dist/', not 'build/'
    - "appspec.yml" # ✅ Ensures CodeDeploy can find appspec.yml
    - "scripts/**" # ✅ Include necessary deployment scripts (if any)
  name: BuildArtifact
  discard-paths: no
